const twilio = require("twilio");
require("dotenv").config();

const TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID;
const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN;
const TWILIO_PHONE_NUMBER = process.env.TWILIO_PHONE_NUMBER;
// WhatsApp sender in the form "whatsapp:+14155238886"
// (Twilio sandbox number for testing, or your approved WhatsApp sender in production)
const TWILIO_WHATSAPP_FROM = process.env.TWILIO_WHATSAPP_FROM;
// Approved WhatsApp Content template SID (starts with "HX...") for the OTP message.
// When set, the OTP is sent via the approved template (required for production /
// business-initiated messages). When unset, falls back to a plain text body (sandbox).
const TWILIO_WHATSAPP_OTP_TEMPLATE_SID = process.env.TWILIO_WHATSAPP_OTP_TEMPLATE_SID;
const DEFAULT_COUNTRY_CODE = process.env.TWILIO_DEFAULT_COUNTRY_CODE || "+91";

const client = twilio(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);

/**
 * Normalize a stored phone number to E.164 format.
 * Phone numbers are stored as plain national numbers (e.g. "9876543210"),
 * so the default country code is prepended when no "+" is present.
 * @param {string} phone
 * @returns {string} E.164 formatted number (e.g. "+919876543210")
 */
const toE164 = (phone) => {
  const trimmed = String(phone).trim().replace(/[\s-]/g, "");
  if (trimmed.startsWith("+")) return trimmed;
  return `${DEFAULT_COUNTRY_CODE}${trimmed}`;
};

const otpBody = (otp) =>
  `Your CryptoGT password reset OTP is ${otp}. It is valid for 10 minutes. Do not share it with anyone.`;

/**
 * Send an OTP to a phone number via Twilio Programmable SMS.
 * @param {string} phone - National phone number (e.g. "9876543210")
 * @param {string} otp - The OTP code to send
 * @returns {Promise<string>} Twilio message SID
 */
const sendOTPSMS = async (phone, otp) => {
  const message = await client.messages.create({
    to: toE164(phone),
    from: TWILIO_PHONE_NUMBER,
    body: otpBody(otp),
  });

  return message.sid;
};

/**
 * Send an OTP to a phone number via Twilio Programmable Messaging over WhatsApp.
 * The OTP is generated by our app (and stored in our DB), so we control the code.
 * NOTE: On the trial sandbox, the recipient must first opt in by sending the
 * "join <code>" message to the sandbox number. In production a WhatsApp sender
 * and an approved OTP template are required.
 * @param {string} phone - National phone number (e.g. "9876543210")
 * @param {string} otp - The OTP code to send
 * @returns {Promise<string>} Twilio message SID
 */
const sendOTPWhatsApp = async (phone, otp) => {
  const params = {
    from: TWILIO_WHATSAPP_FROM,
    to: `whatsapp:${toE164(phone)}`,
  };

  if (TWILIO_WHATSAPP_OTP_TEMPLATE_SID) {
    // Production: send via the approved WhatsApp template.
    // {{1}} in the template body is filled with the OTP.
    params.contentSid = TWILIO_WHATSAPP_OTP_TEMPLATE_SID;
    params.contentVariables = JSON.stringify({ 1: otp });
  } else {
    // Sandbox fallback: plain text body.
    params.body = otpBody(otp);
  }

  const message = await client.messages.create(params);
  return message.sid;
};

module.exports = { sendOTPSMS, sendOTPWhatsApp, toE164 };
