// models/Pin.js
// Shared "pins" collection: pins are generated by the admin backend and
// consumed here when a user activates a hybrid package.
const mongoose = require("mongoose");

const pinSchema = new mongoose.Schema(
  {
    pin: {
      type: String,
      required: true,
      unique: true,
    },
    packageType: {
      type: Number,
      required: true,
      enum: [0, 10, 50, 100],
    },
    activated: {
      type: Boolean,
      default: false,
    },
    usedBy: {
      type: String,
      default: null,
    },
    usedAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Pin", pinSchema);
